Repository simplificamais/vue-polar-bear, pull requests merged in 2021-12, with the labels that each got.

#12 feat: create radio input component
  src/components/Inputs/Radio/Radio.stories.mdx
  src/components/Inputs/Radio/Radio.vue
  src/components/index.js
Labels: enhancement

#11 feat: add eslint
  .eslintrc.js
  package-lock.json
  package.json
Labels: enhancement

#10 Feature/add bootstrap css sizes
  src/components/index.scss
  src/components/widths.scss
Labels: enhancement, help wanted

#17 fix: add pb to name of widths
  src/components/widths.scss
Labels: bug, enhancement
