Repository simplificamais/vue-polar-bear, pull requests merged in 2022-04, with the labels that each got.

#102 Feature/form required validation
  src/components/Miscellaneous/Form/Fields/Array.vue
  src/components/Miscellaneous/Form/Fields/Object.vue
  src/components/Miscellaneous/Form/Fields/ObjectKeys.vue
  src/components/Miscellaneous/Form/Fields/String.vue
  src/components/Miscellaneous/Form/Form.vue
  src/components/utils/entitySchema.js
Labels: enhancement

#104 Refact/vue pb forms
  src/components/Miscellaneous/Form/Fields/String.vue
  src/components/Miscellaneous/Form/Form.vue
Labels: enhancement

#105 [BS-31] - Feature/pb form builder
  src/components/Miscellaneous/FormBuilder/FormBuilder.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
  src/components/Miscellaneous/FormBuilder/formBuilder.stories.mdx
Labels: enhancement

#107 Fix/workflow graph lines
  package-lock.json
  package.json
  src/components/DataVisualization/WorkflowGraph/Lines.vue
  src/components/DataVisualization/WorkflowGraph/WorkflowGraph.vue
Labels: bug

#108 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/DataTable/ListData.vue
  src/components/DataVisualization/DataTable/ListRow.vue
  src/components/DataVisualization/WorkflowGraph/Lines.vue
  src/components/DataVisualization/WorkflowGraph/WorkflowGraph.vue
  src/components/Miscellaneous/Form/Fields/Array.vue
  src/components/Miscellaneous/Form/Fields/File.vue
  src/components/Miscellaneous/Form/Fields/Object.vue
  src/components/Miscellaneous/Form/Fields/ObjectKeys.vue
  src/components/Miscellaneous/Form/Fields/String.vue
  src/components/Miscellaneous/Form/Form.vue
  src/components/Miscellaneous/Form/form.stories.mdx
  src/components/Miscellaneous/FormBuilder/FormBuilder.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
  src/components/Miscellaneous/FormBuilder/formBuilder.stories.mdx
  src/components/utils/entitySchema.js
Labels: merge

#109 Fix/form builder select type
  package-lock.json
  package.json
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
  src/components/index.js
Labels: bug

#110 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
  src/components/index.js
Labels: merge

#111 [FIX] add name prop and change label prop usage
  package-lock.json
  package.json
  src/components/Miscellaneous/FormBuilder/FormBuilder.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: bug

#112 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/FormBuilder/FormBuilder.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: merge

#113 [FIX] pbform image handler
  package-lock.json
  package.json
  src/components/Miscellaneous/Form/Fields/File.vue
Labels: bug

#114 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/Form/Fields/File.vue
Labels: merge

#115 [BS-104] [FIX] order pbform by position prop
  package-lock.json
  package.json
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
  src/components/utils/entitySchema.js
Labels: bug

#116 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
  src/components/utils/entitySchema.js
Labels: merge
