Repository simplificamais/vue-polar-bear, pull requests merged in 2022-03, with the labels that each got.

#62 feat: :technologist: add new custom width to pbModal
  package-lock.json
  package.json
  src/components/NotificationsAndModals/Modal/Modal.vue
Labels: enhancement

#63 Integrate Changes
  package-lock.json
  package.json
  src/components/NotificationsAndModals/Modal/Modal.vue
Labels: merge

#64 fix: make drag and drop container relative to page
  src/components/Layout/DragAndDrop/DragAndDrop.vue
Labels: bug

#65 integrate changes
  package-lock.json
  package.json
  src/components/Layout/DragAndDrop/DragAndDrop.vue
Labels: merge

#89 fix: fixed component in screen to remove scroll
  src/components/MenusAndToolbars/Drawer/Drawer.vue
Labels: bug

#91 feat: add prop of fullscreen in drawer
  src/components/MenusAndToolbars/Drawer/Drawer.vue
Labels: enhancement

#90 Feature/checkbox disabled option
  src/components/Inputs/Checkbox/Checkbox.stories.mdx
  src/components/Inputs/Checkbox/Checkbox.vue
  src/components/Inputs/ThreeStateCheckbox/ThreeStateCheckbox.stories.mdx
  src/components/Inputs/ThreeStateCheckbox/ThreeStateCheckbox.vue
Labels: enhancement

#96 Integrate Changes
  .editorconfig
  package-lock.json
  package.json
  src/components/DataVisualization/DataTable/DataTable.stories.mdx
  src/components/DataVisualization/DataTable/DataTable.vue
  src/components/DataVisualization/DataTable/EntityController.vue
  src/components/DataVisualization/DataTable/ListData.vue
  src/components/DataVisualization/DataTable/ListRow.vue
  src/components/DataVisualization/DataTable/store.js
  src/components/Inputs/Checkbox/Checkbox.stories.mdx
  src/components/Inputs/Checkbox/Checkbox.vue
  src/components/Inputs/CheckboxTree/CheckboxTree.stories.mdx
  src/components/Inputs/CheckboxTree/CheckboxTree.vue
  src/components/Inputs/CheckboxTree/CheckboxTreeController.vue
  src/components/Inputs/ThreeStateCheckbox/ThreeStateCheckbox.stories.mdx
  src/components/Inputs/ThreeStateCheckbox/ThreeStateCheckbox.vue
  src/components/MenusAndToolbars/Drawer/Drawer.vue
  src/components/Miscellaneous/Form/Form.vue
  src/components/index.js
Labels: merge

#97 Fix/Pb form imports
  package-lock.json
  package.json
  src/components/Miscellaneous/Form/Fields/Array.vue
  src/components/Miscellaneous/Form/Fields/Object.vue
  src/components/Miscellaneous/Form/Fields/ObjectKeys.vue
  src/components/Miscellaneous/Form/Form.vue
Labels: bug

#103 [CO-728] Feature/improved lines on WorkflowGraph
  src/components/DataVisualization/WorkflowGraph/Lines.vue
Labels: enhancement
