Repository simplificamais/vue-polar-bear, pull requests merged in 2022-06, with the labels that each got.

#172 Feat/included code owners
  .github/CODEOWNERS
Labels: enhancement

#173 Feature/Pull request template
  .github/PULL_REQUEST_template.md
Labels: enhancement

#176 Integrate Changes
  .github/CODEOWNERS
  .github/PULL_REQUEST_template.md
  package-lock.json
  package.json
  src/components/MenusAndToolbars/Drawer/Drawer.vue
Labels: merge

#177 Fix/Pb forms validations
  package-lock.json
  package.json
  src/components/Miscellaneous/Form/Form.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: bug

#178 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/Form/Form.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: merge

#180 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/CollapseIcon/CollapseIcon.vue
Labels: merge

#181 Feat/pb accordion create
  package-lock.json
  package.json
  src/components/DataVisualization/Accordion/Accordion.stories.mdx
  src/components/DataVisualization/Accordion/Accordion.vue
Labels: enhancement

#182 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/Accordion/Accordion.stories.mdx
  src/components/DataVisualization/Accordion/Accordion.vue
Labels: merge

#184 Integrate Changes
  src/components/index.js
Labels: merge

#186 Integrate Changes
  package-lock.json
  package.json
Labels: merge

#187 Fix/accordion on storybook
  package-lock.json
  package.json
  src/components/DataVisualization/Accordion/Accordion.stories.mdx
Labels: bug
