Repository simplificamais/vue-polar-bear, pull requests merged in 2022-02, with the labels that each got.

#25 feat: creation of workflow graph and storyBook
  src/components/DataVisualization/WorkflowGraph/Balloon.vue
  src/components/DataVisualization/WorkflowGraph/Lines.vue
  src/components/DataVisualization/WorkflowGraph/WorkflowGraph.stories.mdx
  src/components/DataVisualization/WorkflowGraph/WorkflowGraph.vue
Labels: enhancement

#26 feat: add new prop in BreadCrumb
  src/components/Miscellaneous/Breadcrumb/BreadCrumb.stories.mdx
  src/components/Miscellaneous/Breadcrumb/Breadcrumb.vue
Labels: enhancement

#29 feat: creation of new tab
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: enhancement

#30 feat: creation of vertical tabs
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: enhancement

#33 feat: creation of data table component
  src/components/DataVisualization/DataTable/DataTable.stories.mdx
  src/components/DataVisualization/DataTable/DataTable.vue
  src/components/DataVisualization/DataTable/HeaderList.vue
  src/components/DataVisualization/DataTable/ListData.vue
  src/components/DataVisualization/DataTable/ListRow.vue
Labels: enhancement

#34 feat: add a new icon to storybook
  src/plugins/fontawesome.js
Labels: enhancement

#35 Feature/add pb data table in new version
  package-lock.json
  package.json
  src/components/index.js
Labels: enhancement

#36 Fix/data table
  src/components/DataVisualization/DataTable/DataTable.stories.mdx
  src/components/DataVisualization/DataTable/HeaderList.vue
  src/components/DataVisualization/DataTable/ListData.vue
Labels: enhancement

#37 feat: add icon prop and color prop
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: enhancement

#39 fix: add new validations
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: bug

#41 feat: add new version
  package-lock.json
  package.json
Labels: enhancement

#42 Integrate Changes
  package-lock.json
  package.json
Labels: enhancement

#43 feat: add disabled in tabs
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: enhancement

#45 feat: export workflow
  src/components/index.js
Labels: enhancement

#44 feat: add new prop to put empty text
  src/components/DataVisualization/DataTable/DataTable.stories.mdx
  src/components/DataVisualization/DataTable/ListData.vue
Labels: enhancement

#46 fix: workflow
  src/components/index.js
Labels: bug

#49 feat: add new validation in icon
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: enhancement

#50 feat: add new prop in tabs to show abbreviated text
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: enhancement

#51 feat: update vue polar bear
  package-lock.json
  package.json
Labels: enhancement

#52 integrate changes
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: merge

#53 feat: included prop content on slot
  src/components/DataVisualization/WorkflowGraph/WorkflowGraph.vue
Labels: enhancement

#54 fix: adjusted workflow graph height and index
  src/components/DataVisualization/WorkflowGraph/Balloon.vue
  src/components/DataVisualization/WorkflowGraph/Lines.vue
  src/components/DataVisualization/WorkflowGraph/WorkflowGraph.vue
Labels: bug

#55 Feat: Update vue polar bear version
  package-lock.json
  package.json
Labels: enhancement

#56 integrate changes
  package-lock.json
  package.json
  src/components/DataVisualization/WorkflowGraph/Balloon.vue
  src/components/DataVisualization/WorkflowGraph/Lines.vue
  src/components/DataVisualization/WorkflowGraph/WorkflowGraph.vue
Labels: merge

#57 fix: usability
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: enhancement

#59 feat: validates mobile
  src/components/Layout/LayoutGrid/LayoutGrid.stories.mdx
  src/components/Layout/LayoutGrid/LayoutGrid.vue
Labels: enhancement

#60 feat/update vue polar bear version
  package-lock.json
  package.json
Labels: enhancement

#61 integrate changes
  package-lock.json
  package.json
  src/components/Layout/DragAndDrop/DragAndDrop.stories.mdx
  src/components/Layout/DragAndDrop/DragAndDrop.vue
  src/components/Layout/LayoutGrid/LayoutGrid.stories.mdx
  src/components/Layout/LayoutGrid/LayoutGrid.vue
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
  src/components/index.js
  src/plugins/fontawesome.js
Labels: merge
