Repository simplificamais/vue-polar-bear, pull requests merged in 2022-05, with the labels that each got.

#119 [COCA-258] Ajuste componete tabs
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: enhancement

#120 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/Miscellaneous/Tabs/tabs.stories.mdx
Labels: merge

#123 Integrate Changes
  package-lock.json
  package.json
  src/components/Layout/LayoutGrid/LayoutGrid.vue
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: merge

#124 fix: adjust onlyicon css
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: bug

#125 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: merge

#126 [COCA-257] fix: drawer fixes
  src/components/MenusAndToolbars/Drawer/Drawer.vue
Labels: enhancement

#129 fix: adjust pb tabs
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: bug

#130 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: merge

#133 fix: fix tabs cursor
  package-lock.json
  package.json
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: enhancement

#139 feat: removed min height
  src/components/NotificationsAndModals/Modal/Modal.vue
Labels: enhancement

#140 feat: added property to show hint only in overflow
  src/components/Miscellaneous/Hint/Hint.stories.mdx
  src/components/Miscellaneous/Hint/Hint.vue
Labels: enhancement

#142 feat: added sizes in pb button
  src/components/Buttons/Button/Button.stories.mdx
  src/components/Buttons/Button/Button.vue
Labels: enhancement

#148 fix: white space over fields
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: bug

#134 feat: add background light button
  package-lock.json
  package.json
  src/components/Buttons/Button/Button.stories.mdx
  src/components/Buttons/Button/Button.vue
Labels: enhancement

#149 Integrate Changes
  .eslintrc.js
  babel.config.js
  build/build.js
  build/check-versions.js
  build/webpack.config.base.js
  package-lock.json
  package.json
  src/components/Buttons/Button/Button.stories.mdx
  src/components/Buttons/Button/Button.vue
  src/components/Buttons/SortButton/SortButton.vue
  src/components/FiltersAndSearch/Find/Find.vue
  src/components/FiltersAndSearch/SearchInput/SearchInput.vue
  src/components/Inputs/Checkbox/Checkbox.vue
  src/components/Inputs/DateInput/DateInput.stories.mdx
  src/components/Inputs/DateInput/DateInput.vue
  src/components/Inputs/NumberInput/NumberInput.stories.mdx
  src/components/Inputs/NumberInput/NumberInput.vue
  src/components/Inputs/TextArea/TextArea.stories.mdx
  src/components/Inputs/TextArea/TextArea.vue
  src/components/Inputs/TextInput/TextInput.stories.mdx
  src/components/Inputs/TextInput/TextInput.vue
  src/components/Inputs/ThreeStateCheckbox/ThreeStateCheckbox.vue
  src/components/MenusAndToolbars/Sheets/Sheets.stories.mdx
  src/components/MenusAndToolbars/Sheets/Sheets.vue
  src/components/Miscellaneous/Badge/Badge.stories.mdx
  src/components/Miscellaneous/Badge/Badge.vue
  src/components/Miscellaneous/Fieldset/Fieldset.stories.mdx
  src/components/Miscellaneous/FooterNavigation/FooterNavigation.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
  src/components/Miscellaneous/Hint/Hint.stories.mdx
  src/components/Miscellaneous/Hint/Hint.vue
  src/components/Miscellaneous/Tabs/Tabs.vue
  src/components/NotificationsAndModals/Alert/Alert.stories.mdx
  src/components/NotificationsAndModals/Modal/Modal.vue
  src/components/index.scss
  src/components/utils/constants.js
  src/components/variables.scss
Labels: merge

#147 feat: added Pb Table
  package-lock.json
  package.json
  src/components/DataVisualization/Table/Table.stories.mdx
  src/components/DataVisualization/Table/Table.vue
  src/components/DataVisualization/Table/TableHeader.vue
  src/components/DataVisualization/Table/TableRows.vue
  src/components/index.js
Labels: enhancement

#156 feat: add PbIcon into PbBadges
  src/components/Miscellaneous/Badge/Badge.stories.mdx
  src/components/Miscellaneous/Badge/Badge.vue
Labels: enhancement

#163 Integrate Changes
  package.json
  src/components/DataVisualization/WorkflowGraph/Lines.vue
  src/components/Miscellaneous/Form/Fields/CheckGroup.vue
  src/components/Miscellaneous/Form/Form.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: merge

#164 fix: show scroll when it has to many components
  package-lock.json
  package.json
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: bug

#165 Fix/Pbfrom check group label value
  package.json
  src/components/Miscellaneous/Form/Fields/CheckGroup.vue
Labels: bug

#166 Integrate Changes
  package-lock.json
  package.json
  src/components/Miscellaneous/Form/Fields/CheckGroup.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: merge

#168 Fix/pbform required validation
  package-lock.json
  package.json
  src/components/Miscellaneous/Form/Fields/Array.vue
  src/components/Miscellaneous/Form/Fields/CheckGroup.vue
  src/components/Miscellaneous/Form/Fields/Select.vue
  src/components/Miscellaneous/Form/Form.vue
  src/components/Miscellaneous/FormBuilder/FormDrawer.vue
Labels: bug

#170 Fix/layout grid and tabs
  package-lock.json
  package.json
  src/components/Layout/LayoutGrid/LayoutGrid.vue
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: enhancement

#171 Integrate Changes
  package-lock.json
  package.json
  src/components/Layout/LayoutGrid/LayoutGrid.vue
  src/components/Miscellaneous/Tabs/Tabs.vue
Labels: merge
