Repository simplificamais/vue-polar-bear, pull requests merged in 2022-10, with the labels that each got.

#264 feat: sql-pagination-on-pb-table
  src/components/DataVisualization/Table/Table.stories.mdx
  src/components/DataVisualization/Table/Table.vue
  src/components/DataVisualization/Table/TableRows.vue
Labels: enhancement

#263 [SAT-89] - Resolver problemas de grande impacto no PbTable
  src/components/DataVisualization/Table/TableRows.vue
  src/components/utils/constants.js
Labels: bug

#265 [Feat] change PbCard name into PbGalleryCard
  package-lock.json
  package.json
  src/components/DataVisualization/GalleryCard/GalleryCard.stories.mdx
  src/components/DataVisualization/GalleryCard/GalleryCard.vue
  src/components/index.js
Labels: enhancement

#266 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/GalleryCard/GalleryCard.stories.mdx
  src/components/DataVisualization/GalleryCard/GalleryCard.vue
  src/components/DataVisualization/Table/TableRows.vue
  src/components/index.js
  src/components/utils/constants.js
Labels: merge

#267 Feat/refactoring list type on pb table
  package-lock.json
  package.json
  src/components/DataVisualization/Table/Table.stories.mdx
  src/components/DataVisualization/Table/Table.vue
  src/components/DataVisualization/Table/TablePagination.vue
  src/components/DataVisualization/Table/TableRows.vue
Labels: enhancement

#269 fix: adjust pb table layout
  package-lock.json
  package.json
  src/components/DataVisualization/Table/TableRows.vue
Labels: enhancement

#270 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/Table/TableRows.vue
Labels: merge
