Repository simplificamais/vue-polar-bear, pull requests merged in 2022-08, with the labels that each got.

#207 Feat/remove accordion
  package-lock.json
  package.json
  src/components/index.js
Labels: enhancement

#208 Integrate Changes
  package-lock.json
  package.json
  src/components/index.js
Labels: enhancement

#206 feat: new title prop on PbDrawer
  package-lock.json
  package.json
  src/components/MenusAndToolbars/Drawer/Drawer.stories.mdx
  src/components/MenusAndToolbars/Drawer/Drawer.vue
Labels: enhancement

#209 Feat/add accordion in vuepb
  package-lock.json
  package.json
  src/components/index.js
Labels: enhancement

#210 Integrate Changes
  package-lock.json
  package.json
  src/components/MenusAndToolbars/Drawer/Drawer.stories.mdx
  src/components/MenusAndToolbars/Drawer/Drawer.vue
  src/components/index.js
Labels: enhancement

#211 [FEAT] update vue pb
  package-lock.json
  package.json
Labels: enhancement

#212 Integrate Changes
  package-lock.json
  package.json
Labels: enhancement

#213 [FEAT] update storybook
  package-lock.json
  package.json
Labels: enhancement

#214 [FEAT] add validation in click dateinput
  package-lock.json
  package.json
  src/components/Inputs/DateInput/DateInput.vue
Labels: enhancement

#215 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/DateInput/DateInput.vue
Labels: enhancement

#216 feat: adding download icon to vue pb
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: enhancement

#218 Integrate Changes
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: merge

#220 Feat: adding fire icon
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: enhancement

#221 Integrate Changes
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: merge

#222 Fix/validation cursor input
  package-lock.json
  package.json
  src/components/Inputs/NumberInput/NumberInput.vue
Labels: bug

#223 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/NumberInput/NumberInput.vue
Labels: enhancement

#219 feat: improving pbFilterList UI
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.vue
Labels: enhancement

#224 feat: adding mic icon to vuepb
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: enhancement

#225 Integrate Changes
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.vue
  src/plugins/fontawesome.js
Labels: merge

#226 Feature/add new prop number input
  src/components/Inputs/NumberInput/NumberInput.stories.mdx
  src/components/Inputs/NumberInput/NumberInput.vue
Labels: enhancement

#227 Feature/update vue pb new version
  package-lock.json
  package.json
Labels: enhancement

#229 feat: adding multi selector and new interface to PbFilterList
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.stories.mdx
  src/components/FiltersAndSearch/FilterList/FilterList.vue
  src/components/index.scss
Labels: enhancement

#231 Fix/validation date input
  package-lock.json
  package.json
  src/components/Inputs/DateInput/DateInput.vue
Labels: bug

#234 Refact/pb filter list
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.vue
Labels: bug, enhancement

#235 Integrate Changes
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.vue
Labels: merge

#233 feat: adding status badge to pbTable
  package-lock.json
  package.json
  src/components/DataVisualization/Table/Table.stories.mdx
  src/components/DataVisualization/Table/TableRows.vue
  src/components/index.scss
Labels: enhancement

#236 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/Table/Table.stories.mdx
  src/components/DataVisualization/Table/TableRows.vue
  src/components/index.scss
Labels: merge
