Repository simplificamais/vue-polar-bear, pull requests merged in 2023-02, with the labels that each got.

#278 [SIM-525] Feat: refactoring inputs to set background
  package-lock.json
  package.json
  src/components/Inputs/CnpjInput/CnpjInput.stories.mdx
  src/components/Inputs/CnpjInput/CnpjInput.vue
  src/components/Inputs/PhoneInput/PhoneInput.stories.mdx
  src/components/Inputs/PhoneInput/PhoneInput.vue
  src/components/Inputs/TextInput/TextInput.stories.mdx
  src/components/Inputs/TextInput/TextInput.vue
  src/components/index.scss
  src/components/utils/constants.js
  src/components/variables.scss
Labels: enhancement

#279 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/CnpjInput/CnpjInput.stories.mdx
  src/components/Inputs/CnpjInput/CnpjInput.vue
  src/components/Inputs/PhoneInput/PhoneInput.stories.mdx
  src/components/Inputs/PhoneInput/PhoneInput.vue
  src/components/Inputs/TextInput/TextInput.stories.mdx
  src/components/Inputs/TextInput/TextInput.vue
  src/components/index.scss
  src/components/utils/constants.js
  src/components/variables.scss
Labels: merge

#280 [SIM-564] Feat: Refactoring cnpj input to accept other documents
  package-lock.json
  package.json
  src/components/Inputs/CnpjInput/CnpjInput.stories.mdx
  src/components/Inputs/CnpjInput/CnpjInput.vue
  src/components/Inputs/TaxIdInput/TaxIdInput.stories.mdx
  src/components/Inputs/TaxIdInput/TaxIdInput.vue
  src/components/Inputs/TaxIdInput/documentTypes.js
  src/components/Miscellaneous/Form/Fields/String.vue
  src/components/index.js
Labels: enhancement

#281 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/CnpjInput/CnpjInput.stories.mdx
  src/components/Inputs/CnpjInput/CnpjInput.vue
  src/components/Inputs/TaxIdInput/TaxIdInput.stories.mdx
  src/components/Inputs/TaxIdInput/TaxIdInput.vue
  src/components/Inputs/TaxIdInput/documentTypes.js
  src/components/Miscellaneous/Form/Fields/String.vue
  src/components/index.js
Labels: merge

#282 Feat/add emit sort at pb table return default value pb tax id input validation
  package-lock.json
  package.json
  src/components/DataVisualization/Table/Table.vue
  src/components/Inputs/TaxIdInput/TaxIdInput.vue
Labels: enhancement

#284 Fix/overload of emits
  package-lock.json
  package.json
  src/components/Inputs/TaxIdInput/TaxIdInput.vue
Labels: bug

#285 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/TaxIdInput/TaxIdInput.vue
Labels: merge

#286 fix: corrected field formatting
  package-lock.json
  package.json
  src/components/Inputs/TaxIdInput/TaxIdInput.vue
  src/components/Inputs/TaxIdInput/documentTypes.js
Labels: bug

#287 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/TaxIdInput/TaxIdInput.vue
  src/components/Inputs/TaxIdInput/documentTypes.js
Labels: merge
