Repository simplificamais/vue-polar-bear, pull requests merged in 2023-08, with the labels that each got.

#323 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#325 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#326 Feat: change event listener to onloadend instead of onload
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement

#327 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#328 Fix: convert into file before convert to base64
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement

#329 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#330 Fix: container class to style from parent component
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
Labels: enhancement

#331 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
Labels: merge

#332 [Feat] Style adjusts on pb filter list
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.stories.mdx
  src/components/FiltersAndSearch/FilterList/FilterList.vue
  src/components/FiltersAndSearch/SearchInput/SearchInput.vue
  src/components/utils/constants.js
Labels: enhancement

#333 Integrate Changes
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.stories.mdx
  src/components/FiltersAndSearch/FilterList/FilterList.vue
  src/components/FiltersAndSearch/SearchInput/SearchInput.vue
  src/components/utils/constants.js
Labels: merge

#334 [Fix] Adjusted selectDay function
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
Labels: bug

#335 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
Labels: merge

#336 [Fix] Adjusted resetDates function on DateRangePicker
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.stories.mdx
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
Labels: enhancement

#337 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.stories.mdx
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
Labels: merge

#339 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#340 Feat/Fix - Can delete and start new recording properly and audio duration is consistent
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement

#341 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#342 [Feat] Emit clear event on audio input
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement

#345 Feat/emit clear event on trash click
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement

#346 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#347 [Feat] clear audio tracks after stop record
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement

#348 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#349 [Fix] clear audio streams before destroy
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement

#350 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge
