Repository simplificamais/vue-polar-bear, pull requests merged in 2023-11, with the labels that each got.

#369 feat: added background and border props search input
  package-lock.json
  package.json
  src/components/FiltersAndSearch/SearchInput/SearchInput.stories.mdx
  src/components/FiltersAndSearch/SearchInput/SearchInput.vue
Labels: enhancement

#370 feat: changed array column to medium text
  package-lock.json
  package.json
  src/components/DataVisualization/Table/TableRows.vue
Labels: enhancement

#372 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/Table/TableRows.vue
  src/components/FiltersAndSearch/SearchInput/SearchInput.stories.mdx
  src/components/FiltersAndSearch/SearchInput/SearchInput.vue
Labels: merge

#371 fix: add secondary color to constants
  src/components/utils/constants.js
Labels: enhancement

#373 fix: remove border color from text input
  package-lock.json
  package.json
  src/components/Inputs/TextInput/TextInput.vue
  src/components/variables.scss
Labels: bug

#374 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/TextInput/TextInput.vue
  src/components/utils/constants.js
  src/components/variables.scss
Labels: merge

#375 feature/align table rows content center
  package-lock.json
  package.json
  src/components/DataVisualization/Table/TableRows.vue
Labels: enhancement

#376 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/Table/TableRows.vue
Labels: merge

#377 [FEAT][BSWA-1423] New layout grid
  package-lock.json
  package.json
  src/components/Layout/AppLayout/AppLayout.stories.mdx
  src/components/Layout/AppLayout/AppLayout.vue
  src/components/index.js
Labels: enhancement

#379 Integrate changes
  package-lock.json
  package.json
  src/components/Layout/AppLayout/AppLayout.stories.mdx
  src/components/Layout/AppLayout/AppLayout.vue
  src/components/index.js
Labels: merge

#380 [FEAT][BSWA-1423] Improve layout app
  package-lock.json
  package.json
  src/components/Layout/AppLayout/AppLayout.stories.mdx
  src/components/Layout/AppLayout/AppLayout.vue
Labels: enhancement

#381 Integrate changes
  package-lock.json
  package.json
  src/components/Layout/AppLayout/AppLayout.stories.mdx
  src/components/Layout/AppLayout/AppLayout.vue
Labels: merge

#382 Integrate changes
  package-lock.json
  package.json
  src/components/FiltersAndSearch/FilterList/FilterList.vue
Labels: merge
