Repository simplificamais/vue-polar-bear, pull requests merged in 2023-05, with the labels that each got.

#311 [FEAT] :lock: add deepsource code analyzer
  .deepsource.toml
Labels: enhancement

#313 feat: adding pause icon
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: enhancement

#314 Integrate Changes
  .deepsource.toml
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: merge

#312 Fix: resolving calendary errors
  src/components/Inputs/DateRangePicker/DateRangePicker.stories.mdx
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
Labels: bug

#308 feat: creating dateRangePicker
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.stories.mdx
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
  src/components/Inputs/Select/Select.vue
  src/components/index.js
  src/components/index.scss
  src/components/variables.scss
  src/plugins/fontawesome.js
Labels: enhancement

#315 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/DateRangePicker/DateRangePicker.stories.mdx
  src/components/Inputs/DateRangePicker/DateRangePicker.vue
  src/components/Inputs/Select/Select.vue
  src/components/index.js
  src/components/index.scss
  src/components/variables.scss
  src/plugins/fontawesome.js
Labels: merge
