Repository simplificamais/vue-polar-bear, pull requests merged in 2023-09, with the labels that each got.

#351 [FEAT] New component Radial bar
  README.md
  package-lock.json
  package.json
  src/components/DataVisualization/RadialBar/RadialBar.stories.mdx
  src/components/DataVisualization/RadialBar/RadialBar.vue
Labels: enhancement

#353 feat: receive MediaStream as prop and use it to instantiate MediaRecorder
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: enhancement, breaking change

#355 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/AudioInput/AudioInput.stories.mdx
  src/components/Inputs/AudioInput/AudioInput.vue
Labels: merge

#356 feat: adding icons for file-csv and file-audio
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: enhancement

#357 Integrate Changes
  package-lock.json
  package.json
  src/plugins/fontawesome.js
Labels: merge

#358 feat/adding max prop and char counting on text input
  package-lock.json
  package.json
  src/components/Inputs/TextInput/TextInput.stories.mdx
  src/components/Inputs/TextInput/TextInput.vue
Labels: enhancement

#359 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/TextInput/TextInput.stories.mdx
  src/components/Inputs/TextInput/TextInput.vue
Labels: merge

#361 Integrate Changes
  .devcontainer/devcontainer.json
  src/components/DataVisualization/Accordion/Accordion.stories.mdx
  src/components/DataVisualization/Accordion/Accordion.vue
Labels: merge

#364 Integrate Changes
  package-lock.json
  package.json
Labels: merge

#365 fix: radialbar component
  package-lock.json
  package.json
  src/components/DataVisualization/RadialBar/RadialBar.vue
Labels: enhancement
