Repository simplificamais/vue-polar-bear, pull requests merged in 2024-01, with the labels that each got.

#383 feat/new multi select component
  package-lock.json
  package.json
  src/components/Inputs/Checkbox/Checkbox.vue
  src/components/Inputs/MultiSelect/MultiSelect.stories.mdx
  src/components/Inputs/MultiSelect/MultiSelect.vue
  src/components/NotificationsAndModals/CollapseSelect/CollapseSelect.stories.mdx
  src/components/NotificationsAndModals/CollapseSelect/CollapseSelect.vue
  src/components/index.js
  src/components/index.scss
  src/components/utils/constants.js
  src/components/utils/validator.js
  src/plugins/fontawesome.js
Labels: enhancement

#390 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/Checkbox/Checkbox.vue
  src/components/Inputs/MultiSelect/MultiSelect.stories.mdx
  src/components/Inputs/MultiSelect/MultiSelect.vue
  src/components/NotificationsAndModals/CollapseSelect/CollapseSelect.stories.mdx
  src/components/NotificationsAndModals/CollapseSelect/CollapseSelect.vue
  src/components/index.js
  src/components/index.scss
  src/components/utils/constants.js
  src/components/utils/validator.js
  src/plugins/fontawesome.js
Labels: merge

#391 fix: added bg color on options list pb-multi-select
  package-lock.json
  package.json
  src/components/Inputs/MultiSelect/MultiSelect.vue
Labels: bug

#392 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/MultiSelect/MultiSelect.vue
Labels: merge

#393 fix: emit event on unique select
  package-lock.json
  package.json
  src/components/Inputs/MultiSelect/MultiSelect.vue
Labels: bug

#394 Integrate Changes
  package-lock.json
  package.json
  src/components/Inputs/MultiSelect/MultiSelect.vue
Labels: merge

#395 feat: added radius badge option
  package-lock.json
  package.json
  src/components/Miscellaneous/Badge/Badge.stories.mdx
  src/components/Miscellaneous/Badge/Badge.vue
Labels: enhancement
