Repository simplificamais/vue-polar-bear, pull requests merged in 2024-05, with the labels that each got.

#417 Novas props para o PbDialog
  package.json
  src/components/NotificationsAndModals/Dialog/Dialog.stories.mdx
  src/components/NotificationsAndModals/Dialog/Dialog.vue
  src/components/index.scss
Labels: enhancement

#418 Integrate Changes
  package.json
  src/components/NotificationsAndModals/Dialog/Dialog.stories.mdx
  src/components/NotificationsAndModals/Dialog/Dialog.vue
  src/components/index.scss
Labels: merge

#419 Arquivo SCSS para cores
  src/components/scss/_colors.scss
Labels: enhancement

#420 Integrate Changes
  src/components/scss/_colors.scss
Labels: merge

#421 Feature add hover scroll
  package-lock.json
  package.json
  src/components/Inputs/MultiSelect/MultiSelect.vue
  src/components/Inputs/Select/Select.vue
  src/components/index.scss
Labels: enhancement

#422 Integrate Changes (#421)
  package-lock.json
  package.json
  src/components/Inputs/MultiSelect/MultiSelect.vue
  src/components/Inputs/Select/Select.vue
  src/components/index.scss
Labels: merge

#423 [FEAT] new scroll function
  package-lock.json
  package.json
  src/components/DataVisualization/RadialBar/RadialBar.vue
  src/components/index.scss
Labels: enhancement

#424 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/RadialBar/RadialBar.vue
  src/components/index.scss
Labels: merge

#425 [FEAT] Update componets scroll and RadialBar
  package-lock.json
  package.json
  src/components/DataVisualization/RadialBar/RadialBar.vue
  src/components/index.scss
Labels: enhancement

#426 Integrate Changes
  package-lock.json
  package.json
  src/components/DataVisualization/RadialBar/RadialBar.vue
  src/components/index.scss
Labels: merge

#427 [FIX] Scroll size
  package-lock.json
  package.json
  src/components/index.scss
Labels: enhancement

#428 Integrate Changes (#427)
  package-lock.json
  package.json
  src/components/index.scss
Labels: merge

#429 [FIX] Applayout scroll
  package-lock.json
  package.json
  src/components/Layout/AppLayout/AppLayout.vue
Labels: enhancement

#430 Integrate Changes
  package-lock.json
  package.json
  src/components/Layout/AppLayout/AppLayout.vue
Labels: merge

#431 Prop de zoom para o PbCarousel
  package-lock.json
  package.json
  src/components/DataVisualization/Carousel/Carousel.stories.mdx
  src/components/DataVisualization/Carousel/Carousel.vue
  src/components/NotificationsAndModals/Dialog/Dialog.stories.mdx
  src/components/NotificationsAndModals/Dialog/Dialog.vue
Labels: enhancement

#433 [FIX] Zoom no carousel parou de funcionar
  package-lock.json
  package.json
  src/components/DataVisualization/Carousel/Carousel.stories.mdx
  src/components/DataVisualization/Carousel/Carousel.vue
Labels: bug
